### ISSUE TITLE
Help cannot build the template!

### ISSUE THREAD

**Issue by ghost** [equinusocio/xity-starter#34]
I typed npm run build on my Parrot OS terminal and i got:

┌─[✗]─[parrot@catdrouts-parrot-pc]─[~/Desktop/website]
└──╼ $npm run build

> xity-starter@2.0.0 build /home/parrot/Desktop/website
> snowpack build

[22:05:35] [snowpack] ! building files...
[22:05:38] [eleventy] Writing _output/feed.xml from ./pages/feed.njk.
[22:05:39] [eleventy] Writing _output/404.html from ./pages/404.njk.
[22:05:39] [eleventy] Writing _output/blog/index.html from ./pages/blog.njk.
[22:05:39] [eleventy] Writing _output/index.html from ./pages/index.md.
[22:05:39] [eleventy] Writing _output/privacy/index.html from ./pages/privacy.njk.
[22:05:39] [eleventy] Writing _output/blog/tag/all/index.html from ./pages/tags.njk.
Writing _output/blog/take-me-to-russia/index.html from ./pages/blog/take-me-to-russia.md.
[22:05:39] [eleventy] Writing _output/blog/tag/html/index.html from ./pages/tags.njk.
[22:05:39] [eleventy] Writing _output/blog/tag/css/index.html from ./pages/tags.njk.
[22:05:39] [eleventy] Writing _output/blog/tag/posts/index.html from ./pages/tags.njk.
[22:05:39] [eleventy] Copied 6 files / Wrote 10 files in 1.61 seconds (161.0ms each, v0.12.1)
[22:05:40] [eleventy] 24 files will be precached, totaling 0.65 MB.
[22:05:40] [eleventy] Command completed.
[22:05:41] [snowpack] ✔ files built. [6.09s]
[22:05:41] [snowpack] ! building dependencies...
[22:05:41] [snowpack] ✔ dependencies built. [0.00s]
[22:05:41] [snowpack] ! writing to disk...
[22:05:41] [postcss] Command completed.
[22:05:41] [snowpack] ✔ write complete. [0.17s]
[22:05:41] [snowpack] ! optimizing build...
[22:05:42] [snowpack] Not Found in manifest: js/app.js
[22:05:42] [snowpack] Error: Not Found in manifest: js/app.js
    at collectDeepImports (/home/parrot/Desktop/website/node_modules/snowpack/lib/index.js:151553:15)
    at preloadEntrypoint (/home/parrot/Desktop/website/node_modules/snowpack/lib/index.js:151712:9)
    at Object.runBuiltInOptimize (/home/parrot/Desktop/website/node_modules/snowpack/lib/index.js:151954:13)
    at async Object.optimize$1 [as optimize] (/home/parrot/Desktop/website/node_modules/snowpack/lib/index.js:182657:9)
    at async build (/home/parrot/Desktop/website/node_modules/snowpack/lib/index.js:182689:5)
    at async Object.command (/home/parrot/Desktop/website/node_modules/snowpack/lib/index.js:182706:9)
    at async cli (/home/parrot/Desktop/website/node_modules/snowpack/lib/index.js:183016:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! xity-starter@2.0.0 build: `snowpack build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the xity-starter@2.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/parrot/.npm/_logs/2021-04-29T19_04_42_516Z-debug.log

This is in the log file:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'build' ]
2 info using npm@6.14.12
3 info using node@v14.16.1
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle xity-starter@2.0.0~prebuild: xity-starter@2.0.0
6 info lifecycle xity-starter@2.0.0~build: xity-starter@2.0.0
7 verbose lifecycle xity-starter@2.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle xity-starter@2.0.0~build: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/parrot/Desktop/website/node_modules/.bin:/home/parrot/.local/bin:/snap/bin:/usr/sandbox/:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/share/games:/usr/local/sbin:/usr/sbin:/sbin:/home/parrot/.local/bin:/snap/bin:/usr/sandbox/:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/share/games:/usr/local/sbin:/usr/sbin:/sbin:/snap/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
9 verbose lifecycle xity-starter@2.0.0~build: CWD: /home/parrot/Desktop/website
10 silly lifecycle xity-starter@2.0.0~build: Args: [ '-c', 'snowpack build' ]
11 silly lifecycle xity-starter@2.0.0~build: Returned: code: 1  signal: null
12 info lifecycle xity-starter@2.0.0~build: Failed to exec build script
13 verbose stack Error: xity-starter@2.0.0 build: `snowpack build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid xity-starter@2.0.0
15 verbose cwd /home/parrot/Desktop/website
16 verbose Linux 5.10.0-6parrot1-amd64
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build"
18 verbose node v14.16.1
19 verbose npm  v6.14.12
20 error code ELIFECYCLE
21 error errno 1
22 error xity-starter@2.0.0 build: `snowpack build`
22 error Exit status 1
23 error Failed at the xity-starter@2.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Please help !!!!!!**

**Comment by equinusocio** [comment]
Remove the `optimize` key from the snowpack.config file. You can also update the whole config with this https://github.com/equinusocio/xity-starter/blob/main/snowpack.config.js

**Comment by revelt** [comment]
Should we close this issue? The original user account that raised this has been deleted since...
